version: "3.5"
services:

  cve_search:
    image: cve_search
    build:
      context: .
      dockerfile: docker/images/cve_search/dockerfile-cve_search
      args:
        - REPO=cve-search/cve-search
        - BRANCH=master
    hostname: cve_search
    depends_on:
      - redis
      - mongo
    restart: always
    environment:
      - PYTHONUNBUFFERED=TRUE
      - WORKER_SIZE=1
      - MONGODB_HOST=mongo
    ports:
      - '443:5000'
    networks:
      - frontend
      - backend

  redis:
    image: cve_search-redis
    hostname: redis
    restart: always
    build:
      context: .
      dockerfile: docker/images/redis/dockerfile-redis
    volumes:
      - "cve_search_redis_vol:/data"
    expose:
      - 6379
    networks:
      - backend

  mongo:
    image: cve_search-mongo
    hostname: mongo
    restart: always
    build:
      context: .
      dockerfile: docker/images/mongodb/dockerfile-mongo
    volumes:
      - "cve_search_mongodb_vol:/data/db"
    expose:
      - 27017
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  cve_search_mongodb_vol: {}
  cve_search_redis_vol: {}
